services:
  postgres:
    image: 'postgres:15'
    container_name: film-postgres
    environment:
      POSTGRES_DB: filmdb
      POSTGRES_USER: filmuser
      POSTGRES_PASSWORD: filmpass
    ports:
      - '5432:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U filmuser -d filmdb"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    volumes:
      - film_data:/var/lib/postgresql/data
      - ./src/test/resources/1.1-postgress-sakila-schema-compatible.sql:/docker-entrypoint-initdb.d/01-schema.sql:ro
      - ./src/test/resources/2.1-postgres-sakila-film-data.sql:/docker-entrypoint-initdb.d/02-data.sql:ro
    networks:
      - film-network

volumes:
  film_data:
    driver: local

networks:
  film-network:
    driver: bridge 